### ISSUE TITLE
Issues after update of home assistant core-2021.7.x

### ISSUE THREAD

**Issue by Torgrima** [tmjo/ha-norwegiantide#1]
After the july update, I was forced to uninstall a-norwegian tide, because home-assisant became unstable.
No errors in the logs that I can find. 

 After updating to core-2021.7.3, I can not install it from the integration page. 
Worked perfectly before, was installed with hacs.

**Comment by tmjo** [comment]
Thanks for reporting. I noticed something was not working on my own installation too, and it seems to be the versions of dependencies creating an issue. Please try the latest version of the integration (2021.7.1) released just now, it seems to do the trick on my end. Let me know if it works.

**Comment by tmjo** [comment]
Hi @Torgrima; did you test the new release?

**Comment by Torgrima** [comment]
It works good and stable now, also tested in august release core-2021.8.1 :) 

- I do like the new tide cam, but have some small issues with it. If you create multiple tide sensors for different areas thy will get mixed up in the tid cam view if thy are in the same dashbord tab.

- On the phone, tide cam view gets two smaal, with no posibility to zoom in.
