### ISSUE TITLE
Invalid repository

### ISSUE THREAD

**Issue by orjanv** [tmjo/ha-norwegiantide#3]
Getting this message when adding the repository https://github.com/tmjo/ha-norwegiantide

![image](https://user-images.githubusercontent.com/574268/135744059-77751644-9d6d-4a61-9653-0e58adf7baab.png)

**Comment by tmjo** [comment]
Hi @orjanv, I think you're in the wrong place. This is not an add-on but an integration that can be added as a custom repo in HACS.  Try to go to your HACS-installation, click on Integrations and then click the three dots (top right corner) and select custom repositories. If you then continue to add my repo, it should work well.

**Comment by tmjo** [comment]
Closing this since there is no reply.
