### ISSUE TITLE
Home Assistant warning due to deprecated loop keyword argument

### ISSUE THREAD

**Issue by ThoStaKa** [tmjo/ha-norwegiantide#4]
Warning attached here:
"Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for norwegiantide using this method at custom_components/norwegiantide/api.py, line 173: async with async_timeout.timeout(TIMEOUT, loop=asyncio.get_event_loop()):"

**Comment by tmjo** [comment]
Thank you, I will check and fix this. It is strange, because I don't see it myself. Are you on the current version of HA 2021.12?

**Comment by ThoStaKa** [comment]
Yes latest version: core-2021.12.9

**Comment by tmjo** [comment]
Should be fixed now in latest release. Thanks for reporting, I had accidentally turned off logger warning level on my production unit so I didn't see it.
