### ISSUE TITLE
Numpy error in HA 2022.5.0

### ISSUE THREAD

**Issue by ThoStaKa** [tmjo/ha-norwegiantide#5]
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 10:22:17 (1 occurrences)
Last logged: 10:22:17

Setup failed for custom integration norwegiantide: Unable to import component: numpy.core.multiarray failed to import

**Comment by tmjo** [comment]
Hi, thanks for reporting. I saw the same thing yesterday, but didn't find a fix for it. I tried to pin numpy on the same version as is used with other integrations, but still didn't solve it. Hopefully I'll fix it soon!

**Comment by tmjo** [comment]
It seems there is a general problem for some installations with numpy on HA 2022.5 (and 5.1), but [work is in progress](https://github.com/home-assistant/core/issues/71270).

**Comment by tmjo** [comment]
Hi @ThoStaKa, it is working on my end now after update to v2022.5.2. Seems like there was a problem in a wheel on HA side. I'll wait to close this issue until you confirm it is working for you too. Thanks.

**Comment by ThoStaKa** [comment]
Hi, I can confirm that latest update solved the issue for me as well.


lør. 7. mai 2022, 18:14 skrev tmjo ***@***.***>:
